### ISSUE TITLE
Polygon around image

### ISSUE THREAD

**Issue by devsheder** [sfeir-open-source/sfeir-school-theme#24]
As in the speaker slide, add the possibility to set polygon around an image in any slide.
Example :
![Screen Shot 2020-04-07 at 16 24 29](https://user-images.githubusercontent.com/19798549/78680858-4e548b80-78ec-11ea-8a81-e760143d9998.png)

**Comment by JIGANL** [comment]
On peut utiliser çà : 
```css
img[alt*=person] {
  clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);
}
```
