### ISSUE TITLE
[Two Column Layout] Add space between left and right slide

### ISSUE THREAD

**Issue by Xartok** [sfeir-open-source/sfeir-school-theme#52]
At the moment, left and right slide are collapsed, and it is not very pleasant to watch :
![image](https://user-images.githubusercontent.com/2421925/87133604-deadbe00-c297-11ea-965b-ef12da46ec22.png)

As a local workaround I used this css rule : 
```css
.reveal .slides .two-column-layout {
  display: grid;
  grid-column-gap: 20px;
  grid-template-columns: 1fr 1fr;
}
```

This gives this result :
![image](https://user-images.githubusercontent.com/2421925/87134121-84f9c380-c298-11ea-927e-da0ec63d53bb.png)
